### ISSUE TITLE
Add emoji to logo

### ISSUE THREAD

**Issue by DigiVictorian** [scmmmh/the-old-joke-archive#34]
Replace the emoji in the home page banner with one of the ones we commissioned. Queen Victoria laughing will probably be the best option.
<img width="1423" alt="Screenshot 2019-08-22 at 20 18 45" src="https://user-images.githubusercontent.com/7901532/104625694-ec9c2b80-568c-11eb-84b3-1e5768656fc8.png">

**Comment by scmmmh** [comment]
Is this the only format you have the emojis in, or do you have them in any other format as well? SVGs or similar would be the most ideal.

**Comment by scmmmh** [comment]
Implemented in the rewrite
